title = "Vedant Mhatre"
baseURL = 'https://vedant-mhatre.github.io'

# This is what goes in <html lang="">
languageCode = 'en-us'

theme = "hugo-blog-awesome"

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = 'G-FDB8NH5N04' # G-MEASUREMENT_ID

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next line
disqusShortname = ''

[outputs]
  home = [ "HTML", "RSS" ] # Generate RSS

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[menu]
  [[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = '🏠 Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="tech"
    name = '💻 Tech'
    url = '/tech/'
    weight = 20
  # [[menu.main]]
  #   pageRef="food"
  #   name = '🍕 Food'
  #   url = '/food/'
  #   weight = 30
  [[menu.main]]
    pageRef="travel"
    name = '🚗 Travel'
    url = '/travel/'
    weight = 30
  [[menu.main]]
    pageRef="books"
    name = '📚 Books'
    url = '/books/'
    weight = 40
  [[menu.main]]
    pageRef="about"
    name = '🤓 About'
    url = '/about/'
    weight = 50

[params]
  sitename = "Awesome hugo blog"
  defaultColor = "light" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Minimal Hugo blog theme with light and dark mode support"
  mainSections = ['tech','food', 'travel', 'books']
  toc = false # set to false to disable table of contents 'globally'
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatinated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Vedant Mhatre"
  name = "Vedant Mhatre"
  description = "Software Engineer / Tinkerer / Absurdist"

# Allow to override webmanifest options
[params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#f545b1" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[params.browserconfig]
  TileColor = "#f545b1" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/Vedant-Mhatre"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/VedantMhatre19"

# [[params.socialIcons]]
# name = "Rss"
# url = "index.xml"

